env:
  global:
    - CC_TEST_REPORTER_ID=00f17d1777891caebd6f3cdb2a48d202ffb47d655f1436434c77c91d1c742af0
    - COVERAGE=1
language: ruby
rvm:
  - 2.3.1
cache: bundler
services:
  - postgresql
before_script:
  - psql -c 'create database elo_rating_test;' -U postgres
  - bundle exec rails db:setup RAILS_ENV=test
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
