FROM ruby:2.3.0

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

RUN mkdir /app
WORKDIR /app

COPY .ruby-version Gemfile Gemfile.lock ./
RUN bundle install --jobs 3 --retry 5 --without development test

COPY . ./

RUN bundle exec rake assets:precompile RAILS_ENV=production

CMD bundle exec foreman start
