FROM ruby:2.3.0

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

RUN mkdir /app
WORKDIR /app

COPY .ruby-version Gemfile Gemfile.lock ./
RUN bundle install --jobs 3 --retry 5 --without development test

# Set Rails to run in production
ENV RAILS_ENV production 
ENV RACK_ENV production

COPY . ./

RUN bundle exec rake assets:precompile

CMD bundle exec foreman start
