default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: elo_rating_development

test:
  <<: *default
  database: elo_rating_test

production:
  <<: *default
  database: elo_rating_production
